### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by eliastoukolehto** [akskokki/sliding-puzzle-solver#1]
Time of download - 17:18, 20.4.2023 

- The user interface is simple and clear, good!
- The code is well structured; methods don't have multiple jobs and files don't contain multiple classes. good!
- The ability of being able to change board size easily is great for scaling the program.
- You've mentioned plans to expand docstring documentation and enhance the heuristic, both are good ideas.
- The search could print more information than just bound depth. Elapsed time and amount of created nodes and are examples of other useful information.
- The chosen method of pruning (checking if the next node has occurred in the past) is inefficient when the bound is high. Considering how unlikely it is to return to earlier states during search (likelihood of match shrinks with distance), I recommend a less time consuming method. In my own project, I only prohibit creating nodes with the same state as the one before the current one.
- Creating new nodes with deepcopy during recursive search can spend a surprising amount of time. I suggest figuring out a way to get rid of the 'path' attribute altogether in the recursive search method, since the 'moves' attribute contains similar information
- check_win method can be slow since it draws the win state each time the method is called.
- test coverage is low. I've been told that testing user interface isn't necessary in this course

**Comment by akskokki** [comment]
Fantastic feedback, thanks! Really good points about the pruning and deepcopying in particular, I did not realise how inefficient I was being with those.
